export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  ADMINISTRATOR = 'ADMINISTRATOR',
}

export enum UserStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
  REJECTED = 'REJECTED',
}

export enum AttendanceSessionStatus {
  ACTIVE = 'ACTIVE',
  ON_BREAK = 'ON_BREAK',
  COMPLETED = 'COMPLETED',
}

export enum BreakRecordStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum TaskStatus {
  TO_DO = 'TO_DO',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

// A TaskTimeEntry is one segment: RUNNING while active, CLOSED once paused/stopped/switched away.
export enum TaskTimeEntryStatus {
  RUNNING = 'RUNNING',
  CLOSED = 'CLOSED',
}

export enum CorrectionTargetType {
  ATTENDANCE_SESSION = 'ATTENDANCE_SESSION',
  BREAK_RECORD = 'BREAK_RECORD',
  TASK_TIME_ENTRY = 'TASK_TIME_ENTRY',
}

export enum CorrectionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_APPROVED = 'USER_APPROVED',
  USER_REJECTED = 'USER_REJECTED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  CORRECTION_REQUESTED = 'CORRECTION_REQUESTED',
  CORRECTION_APPROVED = 'CORRECTION_APPROVED',
  CORRECTION_REJECTED = 'CORRECTION_REJECTED',
  ADMIN_DIRECT_CORRECTION = 'ADMIN_DIRECT_CORRECTION',
}
